### ISSUE TITLE
is there a way to use components in existing vue2 app??

### ISSUE THREAD

**Issue by mygnu** [rstoenescu/quasar-play#2]
This is actually on steroids man :100:

**Comment by rstoenescu** [comment]
Hi, unfortunately no. All components are meant to stick together since some use the others. A Vue2 port of the framework is underway though.

**Comment by YamenSharaf** [comment]
Has this changed at all? I'm interested in using some Quasar components.

**Comment by rstoenescu** [comment]
Yes, it will be available starting with v0.15. UMD version. Chech forum announcements on v0.15 roadmap. Thanks.
